---
deployment:
  tasks:
    - export PATH=/opt/cpanel/ea-nodejs18/bin:$PATH
    - export DEPLOYPATH=/home/uzinmjcx/public_html/
    - npm install
    - npm run build
    - /bin/cp -R dist/. $DEPLOYPATH
